version: '3.3'
services:
  kartta:
    build:
      context: ./kartta
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "/container/config/kartta/launch", "--watch"]
    volumes:
      - ./container/tools:/container/tools
      - ./container/secrets:/container/secrets
      - ./container/config/kartta:/container/config/kartta
      - ./kartta:/kartta
    ports:
      - "${KARTTA_PORT}"
